import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/ui/Header";
import { cn } from "@/lib/cn";
import { montserratClassname } from "../fonts/fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    montserratClassname,
                    "min-h-screen flex flex-col pb-[100px]"
                )}
            >
                <Header />
                <main className="flex-1 flex flex-col">{children}</main>
            </body>
        </html>
    );
}
